config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  get 'privacy' => 'static_pages#privacy', path: 'privacy-policy'
  get 'terms' => 'static_pages#terms', path: 'terms-of-use'
  get 'dmca' => 'static_pages#dmca', path: 'dmca-policy'
  get 'about' => 'static_pages#about'

  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations", confirmations: "users/confirmations",  unlocks: "users/unlocks"}

  devise_scope :user do
    get 'sign_out', to: 'users/sessions#destroy', path: 'sign-out'
    get 'sign_in', to: 'users/sessions#new', path: 'sign-in'
    get 'register', to: 'users/registrations#new'
    get 'edit_user_settings', to: 'users/registrations#edit', path: 'u/:user_id/settings/edit'
  end

  resources :users, controller: 'users/users', only: [:show], path: 'u'

  resources :artists, controller: 'artists/artists', only: :index

  # TODO: Change path to lyrics/artist/album/track
  resources :artists, controller: 'artists/artists', except: [:index, :new, :create], path: 'lyrics/' do
    resources :albums, controller: 'albums/albums', except: [:index, :new, :create], path: '' do
      resources :tracks, controller: 'tracks/tracks', except: [:index, :new, :create], path: ''
    end
  end

  # TODO: Change path to lyrics/new
  resources :tracks, controller: 'tracks/tracks', only: [:new, :create], path: 'add-lyrics/'

end

app/views/partials/meta/_footer.html.erb
<footer class="full-footer-container">
  <div class="main-container">
    <nav class="footer">
      <div class="center">
        <%= link_to(root_url) do %>
          <div class="nav-links">
            RUBY <i class='far fa-gem'></i> LYRICS
          </div>
        <% end %>
      </div>
      <div class="pb1"></div>
      <div class="center">
        <li><%= link_to "DMCA", dmca_path, class: "nav-links" %></li>

        <li><%= link_to "About", about_path, class: "nav-links" %></li>
        <li><%= link_to "Terms", terms_path, class: "nav-links" %></li>
        <li><%= link_to "Privacy", privacy_path, class: "nav-links" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", user_path(current_user), class: "nav-links" %></li>
          <li><%= link_to 'Settings', edit_user_settings_path(current_user), class: 'nav-links' %></li>
          <li><%= link_to "Sign Out", sign_out_path, class: "nav-links" %></li>
        <% end %>
      </div>
    </nav>

    <div class="pb1"></div>
    
    <div class="footer-disclaimer">
      <%= link_to "Built by Ninth Digital | Buffalo, New York, Earth.", "https://www.ninth.digital" %>
    </div>
    <div class="pb1"></div>
  </div>
</footer>

app/views/partials/meta/_header.html.erb
<header class="header-container pt1 pb1">
  <div class="header-line-height">
    <div class="flex">

      <div class="title-container">
        <div class="header-title-container">
          <%= link_to root_url do %>
            RUBY <i class="secondary-dark far fa-gem"></i> LYRICS
          <% end %>
        </div>
      </div>

      <div class="nav-container right">

        <div class="desktop-only">
          <nav class="header">
            <li><%= link_to 'Artists', artists_path, class: 'nav-links' %></li>
            <li class="site-form-click"><span class="nav-links bold">Add Lyrics</span></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Account', user_path(current_user), class: 'nav-links' %></li>
              <li><%= link_to 'Sign Out', sign_out_path, class: 'nav-links' %></li>
            <% else %>
              <li class="site-form-click"><span class="nav-links bold">Sign In</span></li>
              <li class="register-click"><span class="nav-links-border bold">Register</span></li>
            <% end %>
          </nav>
        </div>

        <div class="mobile-only-block">
          <div id="menu-click-open">
            <i class="fas fa-bars"></i>
          </div>
        </div>

      </div>

    </div>
  </div>
</header>

<div id="menu-container">
  <div class="side-menu">
    <header class="header-container pt1 pb1">
      <div class="header-line-height">

        <div class="flex">

          <div class="title-container">
            <div class="header-title-container">
              <%= link_to root_url do %>
                <span class="white">RUBY <i class="secondary-dark far fa-gem"></i> LYRICS</span>
              <% end %>
            </div>
          </div>

          <div class="nav-container right">
            <div id="menu-click-close">
              <i class="fas fa-times"></i>
            </div>
          </div>

        </div>
      </div>

      <ul>
        <div class="pb3"></div>
        <li><%= link_to 'Artists', artists_path, class: "nav-links" %></li>
        <li class="site-form-click"><span class="nav-links bold">Add Lyrics</span></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Account', user_path(current_user), class: "nav-links" %></li>
          <li><%= link_to 'Settings', edit_user_settings_path(current_user), class: "nav-links" %></li>
          <li><%= link_to 'Sign Out', sign_out_path, class: "nav-links" %></li>
        <% else %>
          <li class="site-form-click"><span class="nav-links bold">Sign In</span></li>
          <li class="register-click"><span class="nav-links bold">Register</span></li>
        <% end %>
      </ul>

    </header>
  </div>
</div>

app/views/partials/meta/_nameplate.html.erb
<% if @artist.present? %>
  <div class="mini-text bold">
    <span class="border-bottom">ARTIST</span>
  </div>
  <div class="pbhalf"></div>
  <div class="title2">
    <%= link_to @artist.name, artist_path(@artist), class: "first-link-dark" %>
  </div>
<% end %>

<% if @album.present? %>
  <div class="pb1"></div>
  <div class="mini-text bold">
    <span class="border-bottom">ALBUM</span>
  </div>
  <div class="pbhalf"></div>
  <div class="title1">
    <%= link_to @album.name, artist_album_path(@artist, @album), class: "secondary-link-dark" %>
  </div>
<% end %>

<% if @track.present? %>
  <div class="pb1"></div>
  <div class="mini-text bold">
    <span class="border-bottom">TRACK</span>
  </div>
  <div class="pbhalf"></div>
  <div class="title1">
    <%= link_to @track.name, artist_album_track_path(@artist, @album, @track), class: "third-link-dark" %>
  </div>
<% end %>

app/views/partials/meta/_ninth_digital_large.html.erb
<div class="pb5"></div>
<div class="nd-container">
  <%= link_to('https://www.ninth.digital') do %>
    <div class="nd-padding">

      <div class="nd-logo-container">
        <div class="nd-logo">
          <%= image_tag("ninth-digital-logo.png", alt: "Ninth Digital Logo") %>
        </div>
      </div>

      <div class="center title2">
        <span class="nd-main bold nd-title-underline">ninth</span><span class="nd-black normal nd-title-underline">.</span><span class="nd-secondary thin nd-title-underline">digital</span>
      </div>

      <div class="pb1"></div>

      <div class="title1 nd-black center">
        A Website Builder
        <div class="pbhalf"></div>
        For Busy People
      </div>

    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_ninth_digital_small.html.erb
<div class="pb5"></div>
<div class="nd-container">
  <%= link_to('https://www.ninth.digital') do %>
    <div class="az-padding">

      <div class="flex">
        <div class="display-small-container">
          <%= image_tag("ninth-digital-logo.png", alt: "Ninth Digital Logo") %>
        </div>
        <div class="az-song-container">
          <div class="az-title1">
            <span class="nd-main bold">ninth</span><span class="nd-black normal">.</span><span class="nd-secondary thin">digital</span>
            <div class="border-bottom"></div>
          </div>
          <div class="mini-text nd-black">
            A Website Builder for Busy People
          </div>
        </div>
      </div>

    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_ninth_fyi_small.html.erb
<div class="pb5"></div>
<div class="nfyi-container">
  <%= link_to('http://www.ninth.fyi') do %>
    <div class="az-padding">

      <div class="flex">
        <div class="display-small-container">
          <%= image_tag("ninth-fyi-logo.png", alt: "Ninth FYI Logo") %>
        </div>
        <div class="az-song-container">
          <div class="az-title1 nfyi-main">
            <span class="nfyi-1">n</span><span class="nfyi-2">i</span><span class="nfyi-3">n</span><span class="nfyi-4">t</span><span class="nfyi-5">h</span><span class="nfyi-6">.</span><span class="nfyi-7">f</span><span class="nfyi-8">y</span><span class="nfyi-9">i</span>
            <div class="border-bottom-white"></div>
          </div>
          <div class="mini-text nfyi-white">
            Free Facts for Your Intelligence!
          </div>
        </div>
      </div>

    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_ninth_recipes_small.html.erb
<div class="pb5"></div>
<div class="nr-container">
  <%= link_to('https://www.ninth.recipes') do %>
    <div class="az-padding">

      <div class="flex">
        <div class="display-small-container">
          <%= image_tag("ninth-recipes-logo.png", alt: "Ninth Recipes Logo") %>
        </div>
        <div class="az-song-container">
          <div class="az-title1 nr-main">
            Ninth Recipes
            <div class="border-bottom"></div>
          </div>
          <div class="mini-text nd-black">
            Share and discover your favorite recipes.
          </div>
        </div>
      </div>

    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_ninthbooks_small.html.erb
<div class="pb5"></div>
<div class="nb-container">
  <%= link_to('http://www.ninthbooks.com') do %>
    <div class="az-padding">

      <div class="flex">
        <div class="display-small-container">
          <%= image_tag("ninth-books-logo.png", alt: "Ninth Books Logo") %>
        </div>
        <div class="az-song-container">
          <div class="az-title1 nb-main">
            Ninth Books
            <div class="border-bottom"></div>
          </div>
          <div class="mini-text nd-black">
            Recommendations from Influential People
          </div>
        </div>
      </div>

    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_play_here.html.erb
<div class="pb5"></div>
<div class="az-container">
  <%= link_to('https://amzn.to/32trGo8') do %>
    <div class="az-padding">

      <div class="flex">
        <div class="az-play-container">
          <i class="far fa-play-circle"></i>
        </div>
        <div class="az-song-container">
          <div class="az-title1">
            <% if @track.present? %>
              <%= @track.name %> by <%= @artist.name %>
            <% elsif @album.present? %>
              <%= @album.name %> by <%= @artist.name %>
            <% elsif @artist.present? %>
              <%= @artist.name %>
            <% end %>
            <div class="border-bottom"></div>
          </div>
          <div class="mini-text">
            Listen with Amazon Music Unlimited <i class="fab fa-amazon"></i>
          </div>
        </div>
      </div>
      
    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_random_lyrics.html.erb
<div class="pb5"></div>
<div class="nd-container">
  <%= link_to('http://www.ninth.fyi') do %>
    <div class="az-padding">
      "Candle sticks in the dark, these are some bodies being burned." - clipping.
    </div>
  <% end %>
</div>
<div class="pb5"></div>

app/views/partials/meta/_register_form.html.erb
<div class="flex">
  <div class="half-container-no-split">
    <div class="title2 white">
      Register
    </div>
  </div>

  <div class="half-container-no-split">
    <div class="right white">
      <div class="close-form-click">
        <i class="fas fa-times"></i>
      </div>
    </div>
  </div>
</div>

<div class="pb5"></div>

<div class="form-container">
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= render "users/shared/error_messages", resource: resource %>

    <%= f.label :email, 'Email' %>
    <div class="pb1"></div>
    <%= f.email_field :email, placeholder: 'Your email address', class: "text-field" %>
    <div class="pb3"></div>
        
    <%= f.label :password, 'Password' %> * <span class="mini-text">Must be at least <%= @minimum_password_length ? @minimum_password_length : "8" %> characters</span>
    <div class="pb1"></div>
    <%= f.password_field :password, placeholder: 'Password', class: "text-field" %>
    <div class="pb3"></div>

    <%= f.submit "Create account", data: { disable_with: 'Creating...' }, class: "main-button" %>
  <% end %>
</div>

<div class="pb5"></div>
<div class="center">
  <%= link_to "Already have an account? Sign in here.", sign_in_path, class: "secondary-link" %>
</div>

app/views/partials/meta/_sign_in_form.html.erb
<div class="flex">
  <div class="half-container-no-split">
    <div class="title2 white">
      Sign in
    </div>
  </div>

  <div class="half-container-no-split">
    <div class="right">
      <span class="close-form-click">
        <i class="fas fa-times"></i>
      </span>
    </div>
  </div>
</div>

<div class="pb5"></div>

<div class="form-container">
  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <%= render "users/shared/error_messages", resource: resource %>

    <%= f.label :email, 'Email' %>
    <div class="pb1"></div>
    <%= f.email_field :email, placeholder: 'Your email address', class: "text-field" %>
    <div class="pb3"></div>
        
    <%= f.label :password, 'Password' %> * <span class="mini-text">Must be at least <%= @minimum_password_length ? @minimum_password_length : "8" %> characters</span>
    <div class="pb1"></div>
    <%= f.password_field :password, placeholder: 'Password', class: "text-field" %>
    <div class="pb3"></div>

    <% if devise_mapping.rememberable? -%>

      <div class="flex">
        <div>
          <label class="remember-inactive" id="remember-tab" for="remember-inactive">Remember me?</label>
          <span class="hidden"><%= f.check_box(:remember_me, id: "remember-inactive") %></span>
        </div>
      </div>

    <% end -%>

    <%= f.submit "Sign in", data: { disable_with: 'Signing in...' }, class: "main-button" %>
  <% end %>
</div>

<div class="pb5"></div>
<div class="center">
  <%= link_to "Don't have an account yet? Register here.", register_path, class: "secondary-link" %>
</div>

app/views/partials/meta/_track_form.html.erb
<div class="flex">
  <div class="half-container-no-split">
    <div class="title2 white">
      Add Lyrics
    </div>
  </div>

  <div class="half-container-no-split">
    <div class="right white">
      <div class="close-form-click">
        <i class="fas fa-times"></i>
      </div>
    </div>
  </div>
</div>

<div class="pb5"></div>

<div class="form-container">
<%= form_for(@uni_track, url: tracks_path) do |f| %>
  <span id="track_errors"><%= render 'partials/errors/track_errors' %></span>

    <%= f.label :artist_name, 'Artist' %>
    <div class="pb1"></div>
    <%= f.text_field :artist_name, placeholder: 'Artist\'s Name', value: (@artist ? @artist.name : ''), class: "text-field" %>
    <div class="pb3"></div>
        
    <%= f.label :album_name, 'Album' %>
    <div class="pb1"></div>
    <%= f.text_field :album_name, placeholder: 'Album\'s Title', value: (@album ? @album.name : ''), class: "text-field" %>
    <div class="pb3"></div>
        
    <%= f.label :name, 'Track' %>
    <div class="pb1"></div>
    <%= f.text_field :name, placeholder: 'Track\'s Title', class: "text-field" %>
    <div class="pb3"></div>
        
    <%= f.label :content, 'Lyrics' %>
    <div class="pb1"></div>
    <%= f.text_area :content, placeholder: 'Track\'s Lyrics', class: "text-area" %>
    <div class="pb3"></div>

    <%= f.submit "Add Lyrics", data: { disable_with: 'Adding...' }, class: "main-button" %>
<% end %>
</div>

app/views/partials/meta/_transition_content.html.erb
<div class="slider-1">
  <%= render 'partials/meta/ninth_digital_small' %>
</div>

<div class="slider-2">
  <%= render 'partials/meta/ninth_recipes_small' %>
</div>

<div class="slider-3">
  <%= render 'partials/meta/ninthbooks_small' %>
</div>

<div class="slider-4">
  <%= render 'partials/meta/play_here' %>
</div>

<div class="slider-5">
  <%= render 'partials/meta/ninth_fyi_small' %>
</div>

<div class="slider-6">
  <%= render 'partials/meta/ninth_digital_small' %>
</div>

<div class="slider-7">
  <%= render 'partials/meta/ninthbooks_small' %>
</div>

<div class="slider-8">
  <%= render 'partials/meta/random_lyrics' %>
</div>

<div class="slider-9">
  <%= render 'partials/meta/play_here' %>
</div>

<div class="slider-10">
  <%= render 'partials/meta/ninth_fyi_small' %>
</div>